### ISSUE TITLE
[Optional] Publish to azure samples browser 

### ISSUE THREAD

**Issue by v-xuto** [Azure-Samples/openai-chat-vision-quickstart#13]
This repository is added to [awesome-azd](https://aka.ms/awesome-azd) site and it is a Microsoft-authored template, we encourage you to [publish it to learn.microsoft.com/samples](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main) if you are interested.

cc @hemarina

**Comment by pamelafox** [comment]
Good idea, I've added the frontmatter (in a comment, since that's now supported) and submitted the sample via the onboarding form.
