### ISSUE TITLE
Uploading image option is not available

### ISSUE THREAD

**Issue by ArpitaisAn0maly** [Azure-Samples/openai-chat-vision-quickstart#8]
Hello,

I don't have an option to upload image. I only have an option to do text chat.  How do I enable upload image feature? I have deployed using codespace

![image](https://github.com/user-attachments/assets/00ee073a-b8c8-40d2-8c51-e8999adba0d6)

**Comment by pamelafox** [comment]
We realized the Codespace links were wrong, pointing to other repo. Fixed now, thanks!
